# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3ce5f9665f5a6e68a0e305d7cceb43dd648644d9a43e5f580fd1cec34e8d36dccab036f2db01df7a720d39c9fee2767090d74916bf3614124607ed562d9e578

test:
  secret_key_base: f567c9add83ea8dd77790cfcec645a7318e0ee12af251379ca7ff243df6ead606363454be310d945f1e1e6eba09324fa0afc6cc86a4e32f7f14f21b38cd8ebdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
